title: homecinema.video
default_lang: en
author:
  name: 'home cinema'
  email: home@cinema.video
taxonomies:
  - category
  - tag
metadata:
  description: ;oiuagshd;oiahgsdoi;asdasd
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
